[package]
name = "monitor-ci"
version = "0.1.0"
authors = ["Yan Vugenfirer <yan@daynix.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
